name: Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Start Kafka and Schema Registry using Docker Compose
      - name: Start Kafka and Schema Registry
        run: |
          docker compose up -d
          # Wait for services to be ready
          ./scripts/wait-for-services.sh
      
      # Setup Java for Order Service
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      # Setup Python for Inventory Service
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      
      # Setup Node.js for Analytics API
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: services/analytics-api/package-lock.json
      
      # Generate code from schemas
      - name: Generate code from schemas
        run: |
          # Create directories for generated code
          mkdir -p services/order-service/src/main/avro
          mkdir -p services/inventory-service/src/generated
          mkdir -p services/analytics-api/src/generated
          
          # Copy schemas to Java service
          cp schemas/v1/*.avsc services/order-service/src/main/avro/
          
          # Generate Java code
          cd services/order-service
          ./gradlew generateAvroJava --info
          cd ../..
          
          # Generate Python code
          cd services/inventory-service
          python scripts/generate_classes.py
          cd ../..
          
          # Generate TypeScript code
          cd services/analytics-api
          npm install
          npm run generate-types
          cd ../..
      
      # Build Order Service
      - name: Build Order Service
        run: |
          cd services/order-service
          ./gradlew build --info
      
      # Build Inventory Service
      - name: Build Inventory Service
        run: |
          cd services/inventory-service
          pip install -e .
      
      # Build Analytics API
      - name: Build Analytics API
        run: |
          cd services/analytics-api
          npm install
          npm run build
      
      # Run smoke tests
      - name: Run smoke tests
        run: |
          # Test if Schema Registry is accessible
          curl --fail http://localhost:8081/subjects || exit 1
          
          # Test if Kafka UI is accessible
          curl --fail --head http://localhost:8080 || echo "Kafka UI not available, but continuing"
          
          # Check Kafka topics
          docker compose exec -T kafka kafka-topics --bootstrap-server kafka:9092 --list || echo "Cannot list Kafka topics, but continuing"
          
          # Verify generated code exists
          test -d services/order-service/build/generated-main-avro-java/com/company/orders || exit 1
          test -f services/inventory-service/src/generated/__init__.py || exit 1
          test -f services/analytics-api/src/generated/index.ts || exit 1
          
          echo "✅ Smoke tests passed!"
      
      # Clean up Docker containers
      - name: Clean up
        if: always()
        run: docker compose down -v
